---
title: "DC3_Sensor"
author: "Ivy Chen, Salwa Ouachtouki"
date: "3/19/2021"
output: html_document
---

1. combine two datasets(join)
2. find the highest Readings for each pollutant
look at the monitor, date find the corresponding wind speed and wind direction
3. Map(Sensor+factory)


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rio)
library(dplyr)
library(ggplot2)
library(lubridate)

sensordata <- import("Sensor Data.xlsx")
meteorologicaldata <- import ("Meteorological Data.xlsx")
monitor <- (sensordata$Monitor)

glimpse(sensordata)
class(sensordata$Chemical) 
```
```{r}
monitor_chemical_reading <- sensordata%>%
  count(Monitor, Chemical)
```

```{r}
ggplot(data = monitor_chemical_reading, aes(x = Monitor, y = n)) +
  geom_point(aes(color = Chemical)) + 
  theme(legend.position = "right") +
  ggtitle("Sensor Data: Monitors & Chemicals") +
  xlab("Monitor") + ylab("Amount of Chemical") +
  xlim("1", "2", "3","4","5","6","7","8","9")
```

<<<<<<< HEAD
The highest wind speed, 6.8 m/s, has the wind direction towards 303.5. The second highest wind speed is 6.7m/s, with a directions towards 282.3. The  6.3 304.2. The monitors that corresponds to the top three strongest wind speed we had above, which detected the most reading of the pollutants are 3 and 4. We infer that these two monitors can lead us to find the factory that is responsible of polluting the environment.


=======
>>>>>>> 7e81b1999daa081cf608ba77f198ac4451c75439
```{r}
chemical_reading <- sensordata %>% 
  group_by(Chemical, Reading) %>% 
  count(Chemical, Reading)

chemical_reading 

chemical_reading.sub1 <- subset(chemical_reading, Reading > 5.0)
chemical_reading.sub1

ggplot(data = chemical_reading.sub1, aes(x = Chemical, y = Reading)) +
  geom_point(aes(color = n)) + 
  scale_y_continuous(breaks = seq(0, 101, by = 5)) +
  theme(legend.position = "right") +
  ggtitle("Sensor Data: Chemical Reading") +
  xlab("Chemical") + ylab("Reading") 

```